[debug] [2017-10-29T23:14:58.790Z] ----------------------------------------------------------------------
[debug] [2017-10-29T23:14:58.792Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --only functions
[debug] [2017-10-29T23:14:58.793Z] CLI Version:   3.13.1
[debug] [2017-10-29T23:14:58.793Z] Platform:      darwin
[debug] [2017-10-29T23:14:58.793Z] Node Version:  v6.9.4
[debug] [2017-10-29T23:14:58.793Z] Time:          Sun Oct 29 2017 19:14:58 GMT-0400 (EDT)
[debug] [2017-10-29T23:14:58.794Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-10-29T23:14:58.806Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-10-29T23:14:58.806Z] > authorizing via signed-in user
[debug] [2017-10-29T23:14:58.808Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/swamphacks-applicants  
 Sun Oct 29 2017 19:14:58 GMT-0400 (EDT)
[debug] [2017-10-29T23:14:59.164Z] <<< HTTP RESPONSE 200
[debug] [2017-10-29T23:14:59.164Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/swamphacks-applicants/tokens  
 Sun Oct 29 2017 19:14:59 GMT-0400 (EDT)
[debug] [2017-10-29T23:14:59.676Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/pablogarces/Desktop/2018-Swamphacks'...
[info] 
[debug] [2017-10-29T23:15:00.003Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:85:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:111:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:16:19
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:660:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9571:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:14:21)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2017-10-29T23:26:37.331Z] ----------------------------------------------------------------------
[debug] [2017-10-29T23:26:37.334Z] Command:       /usr/local/bin/node /usr/local/bin/firebase serve --only functions
[debug] [2017-10-29T23:26:37.334Z] CLI Version:   3.13.1
[debug] [2017-10-29T23:26:37.334Z] Platform:      darwin
[debug] [2017-10-29T23:26:37.334Z] Node Version:  v6.9.4
[debug] [2017-10-29T23:26:37.335Z] Time:          Sun Oct 29 2017 19:26:37 GMT-0400 (EDT)
[debug] [2017-10-29T23:26:37.335Z] ----------------------------------------------------------------------
[debug] 
[debug] [2017-10-29T23:26:37.346Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2017-10-29T23:26:37.347Z] > authorizing via signed-in user
[debug] [2017-10-29T23:26:37.349Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/projects/swamphacks-applicants  
 Sun Oct 29 2017 19:26:37 GMT-0400 (EDT)
[debug] [2017-10-29T23:26:37.719Z] <<< HTTP RESPONSE 200
[debug] [2017-10-29T23:26:37.720Z] >>> HTTP REQUEST GET https://admin.firebase.com/v1/database/swamphacks-applicants/tokens  
 Sun Oct 29 2017 19:26:37 GMT-0400 (EDT)
[debug] [2017-10-29T23:26:38.009Z] <<< HTTP RESPONSE 200
[info] 
[info] === Serving from '/Users/pablogarces/Desktop/2018-Swamphacks'...
[info] 
[debug] [2017-10-29T23:26:38.355Z] Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Object.assertLogsPath (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/local/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:85:32)
    at FunctionsEmulator.start (/usr/local/lib/node_modules/firebase-tools/lib/functionsEmulator.js:111:21)
    at Object.start (/usr/local/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:16:19
    at arrayMap (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:660:23)
    at Function.map (/usr/local/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9571:14)
    at _serve (/usr/local/lib/node_modules/firebase-tools/lib/serve/index.js:14:21)
[error] 
[error] Error: An unexpected error has occurred.
